dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: btXVYEODp64HhXcXBhCJ6qi4ghuGj2WXUHgh/MqP+AAGj71J5Ai2wAc/VWdh5S4RavLX0bwkA1HxvtLg9amzsDEvbcBmBwBOpKiZl5JLXu73ARTymU2HEAHUFmt0y411M9IH9syeX6KAr26264lyLY3I21naaVSgGpAbTjO4chhKqrwzUHl70fs0LN+wqcwDLIeK9VRAx4NVlQwuWLJU1fB4y5IagqX/8rBfBtrKqxJxgzarC/KU7ALcRUQbpnT/NUQVPed9LZzuJOvJYqlYXOuDxEUSpTO8YfmTlIE0CHw+6r1mhwdIC0yv1dkK/IAzhKzn3ZvYcvshb7RCmRDeLnX2IWFF+Dl7pmsXMRST10Lcd6EpHVm3mhL7AStD/ORM7/s3ZR49k7W+/yDk+0CsZduX/UOt16nRffG2DRhBSlWKs37aHEUvjHWZwMMpZ6r+5a+Tgs8vjwPd4WMSOgndn/8R68Ufn0Af1eYOS/d0nDSl8oUoD+qy/UGK6a058txMGv6Bh9hd7ghjVf4BoWht1LXa8fvNZg6fP1VWhcOHlD143M/sslFezKq/ZhiggBfK1p24slGIgl/dnqftFd+CRmFkGCWsW8onyO3FRzsg8lFc/2JXFoLshKNXGr4jQs3ejMLA+vw+8Zs8qyOlEUevMo18OpmGJh/vPbiSWpVujBE=
