dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: iWDqnCFnlKBc2DHMz9zgDwWBhNOZBSiEPOFmgIjai+p6qk/2TLvv6xc67HaSdIvDNW/7Nk4PhYx0QjQ5PqO25oEQrBseYTseG6+vEOzoCg9FKbcsSuh9pChDzsyKRCOaM+2L5/oOckteRfiRhMmEX3wz70N8uUG87T+zyAgmIDSUErqibv+zpBGpLYy2I42pPmtotB/x++cnTPLeVnQJ3LdcP4fCXyveu5L5cN5lFfE4yv/0IRY5Yhq0vho87vziVawMhu3sNvSBMiI/iaG1ANVFEc2TQzdQzHvO+wMPiU7GuHQ7Ec9eJF6O5bFllsmF9Y8NIT4hp0qChgFHHYQ6DsS0glvls37O5hrk575VH68mxReqU2CXwK2fOy0Q2TAmdp6IzFy53a1a5+2WWgkKJ67XShNtP+vaWdFd9FvfRkEdFOj8VuFHcnSwPfy0k1VmUa97phpFZq41u3CMfoTQvuU5BNwFgql9JpksHOIQPMoF18zJk0lDp1sNTK11zWtLNHqQ/CuQJm/w9Mg68HUcx4xeJUdk5ZL+cn7WYZy9/Fp/hCxul6e7+TNo/7JBt9Hd0i0bcCSWzp8v7R7E+t/rU4/fA62V5EOdMY6lqxskselAOnT8siaGM3xQHGf4DoYrAwhC2RcHBP5tTDLTk+IXdsRZ/bxk/NWFh4Jj6keRnQo=
